button_estop_hard: -1
button_estop_gentle: 5
button_power_off: 12 # touch-pad
button_power_on: 13 # ps bottun
button_self_right: 3
button_sit: 1
button_stand: 0
button_release: 8
button_claim: 9
button_stair_mode: -1
button_locomotion_mode: -1
num_buttons: 14
